// Verb data extracted from REGULAR-AND-IRREGULAR-VERBS.pdf (source of truth for this game)
// Structure: { inf, past, pp, es, ca, ipa: { inf, past, pp }, ipaCa }
//   es    = Spanish translation from the source PDF (kept, unused by default — for a possible future language option)
//   ca    = Catalan translation (used by the game)
//   ipa   = British English IPA for infinitive/past/participle
//   ipaCa = Central/Eastern Catalan IPA for the `ca` translation
//
// IPA methodology: transcribed by rule (British RP for English; Central Catalan phonology —
// final -r elided in infinitives, unstressed a/e -> ə, stress marked with ˈ, n+j -> ɲ assimilation,
// etc.) and spot-checked against Wiktionary entries (parlar -> [pərˈla], despertar -> [dəspərˈta],
// menjar -> [məɲˈʒa], ensenyar -> [ənsəˈɲa]) which all matched or corrected the rule set.
// NOT individually verified against a dictionary for all ~240 entries — recommend a native-speaker
// spot check before using in the classroom, especially for less common verbs.
//
// Corrections vs. the source PDF (verified against standard reference tables + live dictionary checks):
//   - "Shear": past reordered to "Sheared/Shore" (sheared is the standard modern past simple;
//     "shore" is archaic/dialectal — confirmed via grammar-monster/Collins). Participle "Shorn" kept
//     (British favors "Shorn"; US favors "Sheared" — noted, not changed).
//   - "Ate": using /eɪt/ as the primary modern RP pronunciation (traditional RP /ɛt/ also valid,
//     confirmed both exist).
const IRREGULAR_VERBS = [
  { inf: "Arise", past: "Arose", pp: "Arisen", es: "Surgir, Levantarse", ca: "Sorgir, Aixecar-se", ipa: { inf: "/əˈraɪz/", past: "/əˈrəʊz/", pp: "/əˈrɪzən/" }, ipaCa: "[suɾˈʒi]" },
  { inf: "Awake", past: "Awoke", pp: "Awoken", es: "Despertarse", ca: "Despertar-se", ipa: { inf: "/əˈweɪk/", past: "/əˈwəʊk/", pp: "/əˈwəʊkən/" }, ipaCa: "[dəspərˈtarsə]" },
  { inf: "Be (am/are/is)", past: "Was/Were", pp: "Been", es: "Ser / Estar", ca: "Ser / Estar", ipa: { inf: "/biː/, /æm/, /ɑː/, /ɪz/", past: "/wɒz/, /wɜː/", pp: "/biːn/" }, ipaCa: "[ˈse] / [əsˈta]" },
  { inf: "Bear", past: "Bore", pp: "Borne/Born", es: "Soportar, dar a luz", ca: "Suportar, donar a llum", ipa: { inf: "/beə/", past: "/bɔː/", pp: "/bɔːn/" }, ipaCa: "[supurˈta]" },
  { inf: "Beat", past: "Beat", pp: "Beaten", es: "Golpear", ca: "Colpejar", ipa: { inf: "/biːt/", past: "/biːt/", pp: "/ˈbiːtən/" }, ipaCa: "[kulpəˈʒa]" },
  { inf: "Become", past: "Became", pp: "Become", es: "Llegar a ser", ca: "Esdevenir", ipa: { inf: "/bɪˈkʌm/", past: "/bɪˈkeɪm/", pp: "/bɪˈkʌm/" }, ipaCa: "[əzdəβəˈni]" },
  { inf: "Begin", past: "Began", pp: "Begun", es: "Empezar", ca: "Començar", ipa: { inf: "/bɪˈɡɪn/", past: "/bɪˈɡæn/", pp: "/bɪˈɡʌn/" }, ipaCa: "[kumənˈsa]" },
  { inf: "Bend", past: "Bent", pp: "Bent", es: "Doblar", ca: "Doblegar", ipa: { inf: "/bend/", past: "/bent/", pp: "/bent/" }, ipaCa: "[dubbləˈɣa]" },
  { inf: "Bet", past: "Bet", pp: "Bet", es: "Apostar", ca: "Apostar", ipa: { inf: "/bet/", past: "/bet/", pp: "/bet/" }, ipaCa: "[əpusˈta]" },
  { inf: "Bind", past: "Bound", pp: "Bound", es: "Atar, encuadernar", ca: "Lligar, enquadernar", ipa: { inf: "/baɪnd/", past: "/baʊnd/", pp: "/baʊnd/" }, ipaCa: "[ʎiˈɣa]" },
  { inf: "Bid", past: "Bid", pp: "Bid", es: "Pujar", ca: "Pujar (en subhasta)", ipa: { inf: "/bɪd/", past: "/bɪd/", pp: "/bɪd/" }, ipaCa: "[puˈʒa]" },
  { inf: "Bite", past: "Bit", pp: "Bitten", es: "Morder", ca: "Mossegar", ipa: { inf: "/baɪt/", past: "/bɪt/", pp: "/ˈbɪtən/" }, ipaCa: "[musəˈɣa]" },
  { inf: "Bleed", past: "Bled", pp: "Bled", es: "Sangrar", ca: "Sagnar", ipa: { inf: "/bliːd/", past: "/bled/", pp: "/bled/" }, ipaCa: "[səɣˈna]" },
  { inf: "Blow", past: "Blew", pp: "Blown", es: "Soplar", ca: "Bufar", ipa: { inf: "/bləʊ/", past: "/bluː/", pp: "/bləʊn/" }, ipaCa: "[buˈfa]" },
  { inf: "Break", past: "Broke", pp: "Broken", es: "Romper", ca: "Trencar", ipa: { inf: "/breɪk/", past: "/brəʊk/", pp: "/ˈbrəʊkən/" }, ipaCa: "[trəŋˈka]" },
  { inf: "Breed", past: "Bred", pp: "Bred", es: "Criar", ca: "Criar", ipa: { inf: "/briːd/", past: "/bred/", pp: "/bred/" }, ipaCa: "[kɾiˈa]" },
  { inf: "Bring", past: "Brought", pp: "Brought", es: "Traer, llevar", ca: "Portar", ipa: { inf: "/brɪŋ/", past: "/brɔːt/", pp: "/brɔːt/" }, ipaCa: "[purˈta]" },
  { inf: "Broadcast", past: "Broadcast", pp: "Broadcast", es: "Radiar", ca: "Emetre, radiar", ipa: { inf: "/ˈbrɔːdkɑːst/", past: "/ˈbrɔːdkɑːst/", pp: "/ˈbrɔːdkɑːst/" }, ipaCa: "[əˈmɛtɾə]" },
  { inf: "Build", past: "Built", pp: "Built", es: "Edificar", ca: "Construir", ipa: { inf: "/bɪld/", past: "/bɪlt/", pp: "/bɪlt/" }, ipaCa: "[kunstɾuˈi]" },
  { inf: "Burn", past: "Burnt/Burned", pp: "Burnt/Burned", es: "Quemar", ca: "Cremar", ipa: { inf: "/bɜːn/", past: "/bɜːnt/, /bɜːnd/", pp: "/bɜːnt/, /bɜːnd/" }, ipaCa: "[kɾəˈma]" },
  { inf: "Burst", past: "Burst", pp: "Burst", es: "Reventar", ca: "Rebentar", ipa: { inf: "/bɜːst/", past: "/bɜːst/", pp: "/bɜːst/" }, ipaCa: "[rəβənˈta]" },
  { inf: "Buy", past: "Bought", pp: "Bought", es: "Comprar", ca: "Comprar", ipa: { inf: "/baɪ/", past: "/bɔːt/", pp: "/bɔːt/" }, ipaCa: "[kumˈpra]" },
  { inf: "Cast", past: "Cast", pp: "Cast", es: "Arrojar", ca: "Llançar", ipa: { inf: "/kɑːst/", past: "/kɑːst/", pp: "/kɑːst/" }, ipaCa: "[ʎənˈsa]" },
  { inf: "Catch", past: "Caught", pp: "Caught", es: "Coger", ca: "Agafar", ipa: { inf: "/kætʃ/", past: "/kɔːt/", pp: "/kɔːt/" }, ipaCa: "[əɣəˈfa]" },
  { inf: "Come", past: "Came", pp: "Come", es: "Venir", ca: "Venir", ipa: { inf: "/kʌm/", past: "/keɪm/", pp: "/kʌm/" }, ipaCa: "[bəˈni]" },
  { inf: "Cost", past: "Cost", pp: "Cost", es: "Costar", ca: "Costar", ipa: { inf: "/kɒst/", past: "/kɒst/", pp: "/kɒst/" }, ipaCa: "[kusˈta]" },
  { inf: "Cut", past: "Cut", pp: "Cut", es: "Cortar", ca: "Tallar", ipa: { inf: "/kʌt/", past: "/kʌt/", pp: "/kʌt/" }, ipaCa: "[təˈʎa]" },
  { inf: "Choose", past: "Chose", pp: "Chosen", es: "Elegir", ca: "Triar", ipa: { inf: "/tʃuːz/", past: "/tʃəʊz/", pp: "/ˈtʃəʊzən/" }, ipaCa: "[tɾiˈa]" },
  { inf: "Cling", past: "Clung", pp: "Clung", es: "Agarrarse", ca: "Aferrar-se", ipa: { inf: "/klɪŋ/", past: "/klʌŋ/", pp: "/klʌŋ/" }, ipaCa: "[əfəˈrarsə]" },
  { inf: "Creep", past: "Crept", pp: "Crept", es: "Arrastrarse", ca: "Arrossegar-se", ipa: { inf: "/kriːp/", past: "/krept/", pp: "/krept/" }, ipaCa: "[ərusəˈɣarsə]" },
  { inf: "Deal", past: "Dealt", pp: "Dealt", es: "Tratar", ca: "Tractar", ipa: { inf: "/diːl/", past: "/delt/", pp: "/delt/" }, ipaCa: "[trəkˈta]" },
  { inf: "Dig", past: "Dug", pp: "Dug", es: "Cavar", ca: "Cavar", ipa: { inf: "/dɪɡ/", past: "/dʌɡ/", pp: "/dʌɡ/" }, ipaCa: "[kəˈβa]" },
  { inf: "Do (does)", past: "Did", pp: "Done", es: "Hacer", ca: "Fer", ipa: { inf: "/duː/, /dʌz/", past: "/dɪd/", pp: "/dʌn/" }, ipaCa: "[ˈfe]" },
  { inf: "Draw", past: "Drew", pp: "Drawn", es: "Dibujar", ca: "Dibuixar", ipa: { inf: "/drɔː/", past: "/druː/", pp: "/drɔːn/" }, ipaCa: "[diβuˈʃa]" },
  { inf: "Dream", past: "Dreamt/Dreamed", pp: "Dreamt/Dreamed", es: "Soñar", ca: "Somiar", ipa: { inf: "/driːm/", past: "/dremt/, /driːmd/", pp: "/dremt/, /driːmd/" }, ipaCa: "[sumiˈa]" },
  { inf: "Drink", past: "Drank", pp: "Drunk", es: "Beber", ca: "Beure", ipa: { inf: "/drɪŋk/", past: "/dræŋk/", pp: "/drʌŋk/" }, ipaCa: "[ˈbɛwɾə]" },
  { inf: "Drive", past: "Drove", pp: "Driven", es: "Conducir", ca: "Conduir", ipa: { inf: "/draɪv/", past: "/drəʊv/", pp: "/ˈdrɪvən/" }, ipaCa: "[kunduˈi]" },
  { inf: "Eat", past: "Ate", pp: "Eaten", es: "Comer", ca: "Menjar", ipa: { inf: "/iːt/", past: "/eɪt/", pp: "/ˈiːtən/" }, ipaCa: "[məɲˈʒa]" },
  { inf: "Fall", past: "Fell", pp: "Fallen", es: "Caer", ca: "Caure", ipa: { inf: "/fɔːl/", past: "/fel/", pp: "/ˈfɔːlən/" }, ipaCa: "[ˈkawɾə]" },
  { inf: "Feed", past: "Fed", pp: "Fed", es: "Alimentar", ca: "Alimentar", ipa: { inf: "/fiːd/", past: "/fed/", pp: "/fed/" }, ipaCa: "[əliməntˈa]" },
  { inf: "Feel", past: "Felt", pp: "Felt", es: "Sentir", ca: "Sentir", ipa: { inf: "/fiːl/", past: "/felt/", pp: "/felt/" }, ipaCa: "[sənˈti]" },
  { inf: "Fight", past: "Fought", pp: "Fought", es: "Luchar", ca: "Lluitar", ipa: { inf: "/faɪt/", past: "/fɔːt/", pp: "/fɔːt/" }, ipaCa: "[ʎuiˈta]" },
  { inf: "Find", past: "Found", pp: "Found", es: "Encontrar", ca: "Trobar", ipa: { inf: "/faɪnd/", past: "/faʊnd/", pp: "/faʊnd/" }, ipaCa: "[truˈβa]" },
  { inf: "Flee", past: "Fled", pp: "Fled", es: "Huir", ca: "Fugir", ipa: { inf: "/fliː/", past: "/fled/", pp: "/fled/" }, ipaCa: "[fuˈʒi]" },
  { inf: "Fly", past: "Flew", pp: "Flown", es: "Volar", ca: "Volar", ipa: { inf: "/flaɪ/", past: "/fluː/", pp: "/fləʊn/" }, ipaCa: "[buˈla]" },
  { inf: "Forbid", past: "Forbade", pp: "Forbidden", es: "Prohibir", ca: "Prohibir", ipa: { inf: "/fəˈbɪd/", past: "/fəˈbæd/, /fəˈbeɪd/", pp: "/fəˈbɪdən/" }, ipaCa: "[pruiˈβi]" },
  { inf: "Forget", past: "Forgot", pp: "Forgotten", es: "Olvidar", ca: "Oblidar", ipa: { inf: "/fəˈɡet/", past: "/fəˈɡɒt/", pp: "/fəˈɡɒtən/" }, ipaCa: "[ubliˈða]" },
  { inf: "Forgive", past: "Forgave", pp: "Forgiven", es: "Perdonar", ca: "Perdonar", ipa: { inf: "/fəˈɡɪv/", past: "/fəˈɡeɪv/", pp: "/fəˈɡɪvən/" }, ipaCa: "[pərðuˈna]" },
  { inf: "Freeze", past: "Froze", pp: "Frozen", es: "Helar", ca: "Gelar", ipa: { inf: "/friːz/", past: "/frəʊz/", pp: "/ˈfrəʊzən/" }, ipaCa: "[ʒəˈla]" },
  { inf: "Get", past: "Got", pp: "Got/Gotten", es: "Obtener", ca: "Obtenir", ipa: { inf: "/ɡet/", past: "/ɡɒt/", pp: "/ɡɒt/, /ˈɡɒtən/" }, ipaCa: "[ubtəˈni]" },
  { inf: "Give", past: "Gave", pp: "Given", es: "Dar", ca: "Donar", ipa: { inf: "/ɡɪv/", past: "/ɡeɪv/", pp: "/ˈɡɪvən/" }, ipaCa: "[duˈna]" },
  { inf: "Go (goes)", past: "Went", pp: "Gone", es: "Ir", ca: "Anar", ipa: { inf: "/ɡəʊ/, /ɡəʊz/", past: "/went/", pp: "/ɡɒn/" }, ipaCa: "[əˈna]" },
  { inf: "Grow", past: "Grew", pp: "Grown", es: "Crecer", ca: "Créixer", ipa: { inf: "/ɡrəʊ/", past: "/ɡruː/", pp: "/ɡrəʊn/" }, ipaCa: "[ˈkɾɛʃə]" },
  { inf: "Grind", past: "Ground", pp: "Ground", es: "Moler", ca: "Moldre", ipa: { inf: "/ɡraɪnd/", past: "/ɡraʊnd/", pp: "/ɡraʊnd/" }, ipaCa: "[ˈmɔldɾə]" },
  { inf: "Hang", past: "Hung", pp: "Hung", es: "Colgar", ca: "Penjar", ipa: { inf: "/hæŋ/", past: "/hʌŋ/", pp: "/hʌŋ/" }, ipaCa: "[pənˈʒa]" },
  { inf: "Have", past: "Had", pp: "Had", es: "Haber o tener", ca: "Haver o Tenir", ipa: { inf: "/hæv/", past: "/hæd/", pp: "/hæd/" }, ipaCa: "[əˈβe u təˈni]" },
  { inf: "Hear", past: "Heard", pp: "Heard", es: "Oir", ca: "Sentir, escoltar", ipa: { inf: "/hɪə/", past: "/hɜːd/", pp: "/hɜːd/" }, ipaCa: "[sənˈti]" },
  { inf: "Hide", past: "Hid", pp: "Hidden", es: "Ocultar", ca: "Amagar", ipa: { inf: "/haɪd/", past: "/hɪd/", pp: "/ˈhɪdən/" }, ipaCa: "[əməˈɣa]" },
  { inf: "Hit", past: "Hit", pp: "Hit", es: "Golpear", ca: "Colpejar", ipa: { inf: "/hɪt/", past: "/hɪt/", pp: "/hɪt/" }, ipaCa: "[kulpəˈʒa]" },
  { inf: "Hold", past: "Held", pp: "Held", es: "Agarrar, celebrar", ca: "Agafar, Celebrar", ipa: { inf: "/həʊld/", past: "/held/", pp: "/held/" }, ipaCa: "[əɣəˈfa]" },
  { inf: "Hurt", past: "Hurt", pp: "Hurt", es: "Herir", ca: "Ferir", ipa: { inf: "/hɜːt/", past: "/hɜːt/", pp: "/hɜːt/" }, ipaCa: "[fəˈɾi]" },
  { inf: "Keep", past: "Kept", pp: "Kept", es: "Conservar", ca: "Conservar", ipa: { inf: "/kiːp/", past: "/kept/", pp: "/kept/" }, ipaCa: "[kunsərˈba]" },
  { inf: "Know", past: "Knew", pp: "Known", es: "Saber, conocer", ca: "Saber, Conèixer", ipa: { inf: "/nəʊ/", past: "/njuː/", pp: "/nəʊn/" }, ipaCa: "[səˈβe]" },
  { inf: "Kneel", past: "Knelt", pp: "Knelt", es: "Arrodillarse", ca: "Agenollar-se", ipa: { inf: "/niːl/", past: "/nelt/", pp: "/nelt/" }, ipaCa: "[əʒənuˈʎarsə]" },
  { inf: "Knit", past: "Knit", pp: "Knit", es: "Hacer punto", ca: "Fer punt de mitja", ipa: { inf: "/nɪt/", past: "/nɪt/", pp: "/nɪt/" }, ipaCa: "[ˈfe]" },
  { inf: "Lay", past: "Laid", pp: "Laid", es: "Poner", ca: "Posar", ipa: { inf: "/leɪ/", past: "/leɪd/", pp: "/leɪd/" }, ipaCa: "[puˈza]" },
  { inf: "Lead", past: "Led", pp: "Led", es: "Conducir", ca: "Conduir, Liderar", ipa: { inf: "/liːd/", past: "/led/", pp: "/led/" }, ipaCa: "[kunduˈi]" },
  { inf: "Lean", past: "Leant", pp: "Leant", es: "Apoyarse", ca: "Recolzar-se", ipa: { inf: "/liːn/", past: "/lent/", pp: "/lent/" }, ipaCa: "[rəkulˈzarsə]" },
  { inf: "Leap", past: "Leapt", pp: "Leapt", es: "Brincar", ca: "Saltar", ipa: { inf: "/liːp/", past: "/lept/", pp: "/lept/" }, ipaCa: "[səlˈta]" },
  { inf: "Learn", past: "Learnt/Learned", pp: "Learnt/Learned", es: "Aprender", ca: "Aprendre", ipa: { inf: "/lɜːn/", past: "/lɜːnt/, /lɜːnd/", pp: "/lɜːnt/, /lɜːnd/" }, ipaCa: "[əˈpɾɛndɾə]" },
  { inf: "Leave", past: "Left", pp: "Left", es: "Dejar", ca: "Deixar, Marxar", ipa: { inf: "/liːv/", past: "/left/", pp: "/left/" }, ipaCa: "[dəˈʃa]" },
  { inf: "Lend", past: "Lent", pp: "Lent", es: "Prestar", ca: "Prestar", ipa: { inf: "/lend/", past: "/lent/", pp: "/lent/" }, ipaCa: "[prəsˈta]" },
  { inf: "Let", past: "Let", pp: "Let", es: "Permitir", ca: "Permetre", ipa: { inf: "/let/", past: "/let/", pp: "/let/" }, ipaCa: "[pərˈmɛtɾə]" },
  { inf: "Lie", past: "Lay", pp: "Lain", es: "Echarse", ca: "Ajeure's", ipa: { inf: "/laɪ/", past: "/leɪ/", pp: "/leɪn/" }, ipaCa: "[əˈʒɛwɾəs]" },
  { inf: "Light", past: "Lit", pp: "Lit", es: "Encender", ca: "Encendre", ipa: { inf: "/laɪt/", past: "/lɪt/", pp: "/lɪt/" }, ipaCa: "[ənˈsɛndɾə]" },
  { inf: "Lose", past: "Lost", pp: "Lost", es: "Perder", ca: "Perdre", ipa: { inf: "/luːz/", past: "/lɒst/", pp: "/lɒst/" }, ipaCa: "[ˈpɛrdɾə]" },
  { inf: "Make", past: "Made", pp: "Made", es: "Hacer", ca: "Fer", ipa: { inf: "/meɪk/", past: "/meɪd/", pp: "/meɪd/" }, ipaCa: "[ˈfe]" },
  { inf: "Mean", past: "Meant", pp: "Meant", es: "Significar", ca: "Significar", ipa: { inf: "/miːn/", past: "/ment/", pp: "/ment/" }, ipaCa: "[siɣnifiˈka]" },
  { inf: "Meet", past: "Met", pp: "Met", es: "Encontrar", ca: "Trobar-se", ipa: { inf: "/miːt/", past: "/met/", pp: "/met/" }, ipaCa: "[truˈβarsə]" },
  { inf: "Mistake", past: "Mistook", pp: "Mistaken", es: "Equivocar", ca: "Equivocar", ipa: { inf: "/mɪˈsteɪk/", past: "/mɪˈstʊk/", pp: "/mɪˈsteɪkən/" }, ipaCa: "[əkiβuˈka]" },
  { inf: "Overcome", past: "Overcame", pp: "Overcome", es: "Vencer", ca: "Vèncer", ipa: { inf: "/ˌəʊvəˈkʌm/", past: "/ˌəʊvəˈkeɪm/", pp: "/ˌəʊvəˈkʌm/" }, ipaCa: "[ˈbɛnsə]" },
  { inf: "Pay", past: "Paid", pp: "Paid", es: "Pagar", ca: "Pagar", ipa: { inf: "/peɪ/", past: "/peɪd/", pp: "/peɪd/" }, ipaCa: "[pəˈɣa]" },
  { inf: "Put", past: "Put", pp: "Put", es: "Poner", ca: "Posar", ipa: { inf: "/pʊt/", past: "/pʊt/", pp: "/pʊt/" }, ipaCa: "[puˈza]" },
  { inf: "Read", past: "Read", pp: "Read", es: "Leer", ca: "Llegir", ipa: { inf: "/riːd/", past: "/red/", pp: "/red/" }, ipaCa: "[ʎəˈʒi]" },
  { inf: "Ride", past: "Rode", pp: "Ridden", es: "Montar", ca: "Muntar", ipa: { inf: "/raɪd/", past: "/rəʊd/", pp: "/ˈrɪdən/" }, ipaCa: "[munˈta]" },
  { inf: "Ring", past: "Rang", pp: "Rung", es: "Llamar", ca: "Trucar, Sonar", ipa: { inf: "/rɪŋ/", past: "/ræŋ/", pp: "/rʌŋ/" }, ipaCa: "[truˈka]" },
  { inf: "Rise", past: "Rose", pp: "Risen", es: "Levantarse", ca: "Aixecar-se", ipa: { inf: "/raɪz/", past: "/rəʊz/", pp: "/ˈrɪzən/" }, ipaCa: "[əʃəˈkarsə]" },
  { inf: "Run", past: "Ran", pp: "Run", es: "Correr", ca: "Córrer", ipa: { inf: "/rʌn/", past: "/ræn/", pp: "/rʌn/" }, ipaCa: "[ˈkɔrə]" },
  { inf: "Say", past: "Said", pp: "Said", es: "Decir", ca: "Dir", ipa: { inf: "/seɪ/", past: "/sed/", pp: "/sed/" }, ipaCa: "[ˈdi]" },
  { inf: "See", past: "Saw", pp: "Seen", es: "Ver", ca: "Veure", ipa: { inf: "/siː/", past: "/sɔː/", pp: "/siːn/" }, ipaCa: "[ˈbɛwɾə]" },
  { inf: "Seek", past: "Sought", pp: "Sought", es: "Buscar", ca: "Buscar", ipa: { inf: "/siːk/", past: "/sɔːt/", pp: "/sɔːt/" }, ipaCa: "[busˈka]" },
  { inf: "Sell", past: "Sold", pp: "Sold", es: "Vender", ca: "Vendre", ipa: { inf: "/sel/", past: "/səʊld/", pp: "/səʊld/" }, ipaCa: "[ˈbɛndɾə]" },
  { inf: "Send", past: "Sent", pp: "Sent", es: "Enviar", ca: "Enviar", ipa: { inf: "/send/", past: "/sent/", pp: "/sent/" }, ipaCa: "[əmbiˈa]" },
  { inf: "Set", past: "Set", pp: "Set", es: "Poner(se)", ca: "Posar", ipa: { inf: "/set/", past: "/set/", pp: "/set/" }, ipaCa: "[puˈza]" },
  { inf: "Sew", past: "Sewed", pp: "Sewed/Sewn", es: "Coser", ca: "Cosir", ipa: { inf: "/səʊ/", past: "/səʊd/", pp: "/səʊd/, /səʊn/" }, ipaCa: "[kuˈzi]" },
  { inf: "Shake", past: "Shook", pp: "Shaken", es: "Sacudir", ca: "Sacsejar", ipa: { inf: "/ʃeɪk/", past: "/ʃʊk/", pp: "/ˈʃeɪkən/" }, ipaCa: "[səksəˈʒa]" },
  { inf: "Shear", past: "Sheared/Shore", pp: "Shorn", es: "Esquilar", ca: "Esquilar", ipa: { inf: "/ʃɪə/", past: "/ʃɪəd/, /ʃɔː/", pp: "/ʃɔːn/" }, ipaCa: "[əskiˈla]" },
  { inf: "Shine", past: "Shone", pp: "Shone", es: "Brillar", ca: "Brillar", ipa: { inf: "/ʃaɪn/", past: "/ʃɒn/", pp: "/ʃɒn/" }, ipaCa: "[briˈʎa]" },
  { inf: "Shoot", past: "Shot", pp: "Shot", es: "Disparar", ca: "Disparar", ipa: { inf: "/ʃuːt/", past: "/ʃɒt/", pp: "/ʃɒt/" }, ipaCa: "[dispəˈra]" },
  { inf: "Show", past: "Showed", pp: "Shown", es: "Mostrar", ca: "Mostrar", ipa: { inf: "/ʃəʊ/", past: "/ʃəʊd/", pp: "/ʃəʊn/" }, ipaCa: "[musˈtra]" },
  { inf: "Shrink", past: "Shrank", pp: "Shrunk", es: "Encogerse", ca: "Encongir-se", ipa: { inf: "/ʃrɪŋk/", past: "/ʃræŋk/", pp: "/ʃrʌŋk/" }, ipaCa: "[əŋkunˈʒirsə]" },
  { inf: "Shut", past: "Shut", pp: "Shut", es: "Cerrar", ca: "Tancar", ipa: { inf: "/ʃʌt/", past: "/ʃʌt/", pp: "/ʃʌt/" }, ipaCa: "[təŋˈka]" },
  { inf: "Sing", past: "Sang", pp: "Sung", es: "Cantar", ca: "Cantar", ipa: { inf: "/sɪŋ/", past: "/sæŋ/", pp: "/sʌŋ/" }, ipaCa: "[kənˈta]" },
  { inf: "Sink", past: "Sank", pp: "Sunk", es: "Hundir", ca: "Enfonsar", ipa: { inf: "/sɪŋk/", past: "/sæŋk/", pp: "/sʌŋk/" }, ipaCa: "[əɱfunˈsa]" },
  { inf: "Sit", past: "Sat", pp: "Sat", es: "Sentarse", ca: "Seure", ipa: { inf: "/sɪt/", past: "/sæt/", pp: "/sæt/" }, ipaCa: "[ˈsɛwɾə]" },
  { inf: "Sleep", past: "Slept", pp: "Slept", es: "Dormir", ca: "Dormir", ipa: { inf: "/sliːp/", past: "/slept/", pp: "/slept/" }, ipaCa: "[durˈmi]" },
  { inf: "Slide", past: "Slid", pp: "Slid", es: "Resbalar", ca: "Relliscar", ipa: { inf: "/slaɪd/", past: "/slɪd/", pp: "/slɪd/" }, ipaCa: "[rəʎisˈka]" },
  { inf: "Smell", past: "Smelt", pp: "Smelt", es: "Oler", ca: "Olorar", ipa: { inf: "/smel/", past: "/smelt/", pp: "/smelt/" }, ipaCa: "[uluˈra]" },
  { inf: "Sow", past: "Sowed", pp: "Sowed/Sown", es: "Sembrar", ca: "Sembrar", ipa: { inf: "/səʊ/", past: "/səʊd/", pp: "/səʊd/, /səʊn/" }, ipaCa: "[səmˈbra]" },
  { inf: "Speak", past: "Spoke", pp: "Spoken", es: "Hablar", ca: "Parlar", ipa: { inf: "/spiːk/", past: "/spəʊk/", pp: "/ˈspəʊkən/" }, ipaCa: "[pərˈla]" },
  { inf: "Speed", past: "Sped", pp: "Sped", es: "Acelerar", ca: "Accelerar", ipa: { inf: "/spiːd/", past: "/sped/", pp: "/sped/" }, ipaCa: "[əksələˈra]" },
  { inf: "Spell", past: "Spelt", pp: "Spelt", es: "Deletrear", ca: "Lletrejar", ipa: { inf: "/spel/", past: "/spelt/", pp: "/spelt/" }, ipaCa: "[ʎətrəˈʒa]" },
  { inf: "Spend", past: "Spent", pp: "Spent", es: "Gastar", ca: "Gastar", ipa: { inf: "/spend/", past: "/spent/", pp: "/spent/" }, ipaCa: "[ɣəsˈta]" },
  { inf: "Spill", past: "Spilt/Spilled", pp: "Spilt/Spilled", es: "Derramar", ca: "Vessar", ipa: { inf: "/spɪl/", past: "/spɪlt/, /spɪld/", pp: "/spɪlt/, /spɪld/" }, ipaCa: "[bəˈsa]" },
  { inf: "Spin", past: "Spun", pp: "Spun", es: "Hilar", ca: "Filar", ipa: { inf: "/spɪn/", past: "/spʌn/", pp: "/spʌn/" }, ipaCa: "[fiˈla]" },
  { inf: "Spit", past: "Spat", pp: "Spat", es: "Escupir", ca: "Escopir", ipa: { inf: "/spɪt/", past: "/spæt/", pp: "/spæt/" }, ipaCa: "[əskuˈpi]" },
  { inf: "Split", past: "Split", pp: "Split", es: "Hender, partir, rajar", ca: "Partir", ipa: { inf: "/splɪt/", past: "/splɪt/", pp: "/splɪt/" }, ipaCa: "[pərˈti]" },
  { inf: "Spoil", past: "Spoilt/Spoiled", pp: "Spoilt/Spoiled", es: "Estropear", ca: "Espatllar", ipa: { inf: "/spɔɪl/", past: "/spɔɪlt/, /spɔɪld/", pp: "/spɔɪlt/, /spɔɪld/" }, ipaCa: "[əspəˈʎa]" },
  { inf: "Spread", past: "Spread", pp: "Spread", es: "Extender", ca: "Estendre", ipa: { inf: "/spred/", past: "/spred/", pp: "/spred/" }, ipaCa: "[əsˈtɛndɾə]" },
  { inf: "Spring", past: "Sprang", pp: "Sprung", es: "Saltar", ca: "Saltar", ipa: { inf: "/sprɪŋ/", past: "/spræŋ/", pp: "/sprʌŋ/" }, ipaCa: "[səlˈta]" },
  { inf: "Stand", past: "Stood", pp: "Stood", es: "Estar en pie", ca: "Estar dret", ipa: { inf: "/stænd/", past: "/stʊd/", pp: "/stʊd/" }, ipaCa: "[əsˈta ˈdɾɛt]" },
  { inf: "Steal", past: "Stole", pp: "Stolen", es: "Robar", ca: "Robar", ipa: { inf: "/stiːl/", past: "/stəʊl/", pp: "/ˈstəʊlən/" }, ipaCa: "[ruˈβa]" },
  { inf: "Stick", past: "Stuck", pp: "Stuck", es: "Pegar, engomar", ca: "Enganxar", ipa: { inf: "/stɪk/", past: "/stʌk/", pp: "/stʌk/" }, ipaCa: "[əŋɡənˈʃa]" },
  { inf: "Sting", past: "Stung", pp: "Stung", es: "Picar", ca: "Picar", ipa: { inf: "/stɪŋ/", past: "/stʌŋ/", pp: "/stʌŋ/" }, ipaCa: "[piˈka]" },
  { inf: "Stink", past: "Stank/Stunk", pp: "Stunk", es: "Apestar", ca: "Fer pudor", ipa: { inf: "/stɪŋk/", past: "/stæŋk/, /stʌŋk/", pp: "/stʌŋk/" }, ipaCa: "[ˈfe puˈðo]" },
  { inf: "Stride", past: "Strode", pp: "Stridden", es: "Dar zancadas", ca: "Fer gambades", ipa: { inf: "/straɪd/", past: "/strəʊd/", pp: "/ˈstrɪdən/" }, ipaCa: "[ˈfe ɣəmˈbaðəs]" },
  { inf: "Strike", past: "Struck", pp: "Struck", es: "Golpear", ca: "Colpejar", ipa: { inf: "/straɪk/", past: "/strʌk/", pp: "/strʌk/" }, ipaCa: "[kulpəˈʒa]" },
  { inf: "Swear", past: "Swore", pp: "Sworn", es: "Jurar", ca: "Jurar", ipa: { inf: "/sweə/", past: "/swɔː/", pp: "/swɔːn/" }, ipaCa: "[ʒuˈra]" },
  { inf: "Sweat", past: "Sweat", pp: "Sweat", es: "Sudar", ca: "Suar", ipa: { inf: "/swet/", past: "/swet/", pp: "/swet/" }, ipaCa: "[suˈa]" },
  { inf: "Sweep", past: "Swept", pp: "Swept", es: "Barrer", ca: "Escombrar", ipa: { inf: "/swiːp/", past: "/swept/", pp: "/swept/" }, ipaCa: "[əskumˈbra]" },
  { inf: "Swell", past: "Swelled", pp: "Swollen", es: "Hinchar", ca: "Inflar-se", ipa: { inf: "/swel/", past: "/sweld/", pp: "/ˈswəʊlən/" }, ipaCa: "[iɱˈflarsə]" },
  { inf: "Swim", past: "Swam", pp: "Swum", es: "Nadar", ca: "Nedar", ipa: { inf: "/swɪm/", past: "/swæm/", pp: "/swʌm/" }, ipaCa: "[nəˈða]" },
  { inf: "Swing", past: "Swung", pp: "Swung", es: "Columpiarse", ca: "Gronxar-se", ipa: { inf: "/swɪŋ/", past: "/swʌŋ/", pp: "/swʌŋ/" }, ipaCa: "[gɾunˈʃarsə]" },
  { inf: "Take", past: "Took", pp: "Taken", es: "Coger", ca: "Agafar", ipa: { inf: "/teɪk/", past: "/tʊk/", pp: "/ˈteɪkən/" }, ipaCa: "[əɣəˈfa]" },
  { inf: "Teach", past: "Taught", pp: "Taught", es: "Enseñar", ca: "Ensenyar", ipa: { inf: "/tiːtʃ/", past: "/tɔːt/", pp: "/tɔːt/" }, ipaCa: "[ənsəˈɲa]" },
  { inf: "Tear", past: "Tore", pp: "Torn", es: "Rasgar", ca: "Estripar", ipa: { inf: "/teə/", past: "/tɔː/", pp: "/tɔːn/" }, ipaCa: "[əstriˈpa]" },
  { inf: "Tell", past: "Told", pp: "Told", es: "Decir", ca: "Dir", ipa: { inf: "/tel/", past: "/təʊld/", pp: "/təʊld/" }, ipaCa: "[ˈdi]" },
  { inf: "Think", past: "Thought", pp: "Thought", es: "Pensar", ca: "Pensar", ipa: { inf: "/θɪŋk/", past: "/θɔːt/", pp: "/θɔːt/" }, ipaCa: "[pənˈsa]" },
  { inf: "Throw", past: "Threw", pp: "Thrown", es: "Arrojar, tirar", ca: "Llançar", ipa: { inf: "/θrəʊ/", past: "/θruː/", pp: "/θrəʊn/" }, ipaCa: "[ʎənˈsa]" },
  { inf: "Thrust", past: "Thrust", pp: "Thrust", es: "Introducir", ca: "Introduir", ipa: { inf: "/θrʌst/", past: "/θrʌst/", pp: "/θrʌst/" }, ipaCa: "[intɾuðuˈi]" },
  { inf: "Tread", past: "Trod", pp: "Trodden", es: "Pisar, hollar", ca: "Trepitjar", ipa: { inf: "/tred/", past: "/trɒd/", pp: "/ˈtrɒdən/" }, ipaCa: "[trəpiˈdʒa]" },
  { inf: "Understand", past: "Understood", pp: "Understood", es: "Entender", ca: "Entendre", ipa: { inf: "/ˌʌndəˈstænd/", past: "/ˌʌndəˈstʊd/", pp: "/ˌʌndəˈstʊd/" }, ipaCa: "[ənˈtɛndɾə]" },
  { inf: "Undergo", past: "Underwent", pp: "Undergone", es: "Sufrir", ca: "Patir", ipa: { inf: "/ˌʌndəˈɡəʊ/", past: "/ˌʌndəˈwent/", pp: "/ˌʌndəˈɡɒn/" }, ipaCa: "[pəˈti]" },
  { inf: "Undertake", past: "Undertook", pp: "Undertaken", es: "Emprender", ca: "Emprendre", ipa: { inf: "/ˌʌndəˈteɪk/", past: "/ˌʌndəˈtʊk/", pp: "/ˌʌndəˈteɪkən/" }, ipaCa: "[əmˈpɾɛndɾə]" },
  { inf: "Wake", past: "Woke", pp: "Woken", es: "Despertarse", ca: "Despertar-se", ipa: { inf: "/weɪk/", past: "/wəʊk/", pp: "/ˈwəʊkən/" }, ipaCa: "[dəspərˈtarsə]" },
  { inf: "Wear", past: "Wore", pp: "Worn", es: "Llevar puesto", ca: "Portar posat", ipa: { inf: "/weə/", past: "/wɔː/", pp: "/wɔːn/" }, ipaCa: "[purˈta puˈzat]" },
  { inf: "Weave", past: "Wove", pp: "Woven", es: "Tejer", ca: "Teixir", ipa: { inf: "/wiːv/", past: "/wəʊv/", pp: "/ˈwəʊvən/" }, ipaCa: "[təˈʃi]" },
  { inf: "Weep", past: "Wept", pp: "Wept", es: "Llorar", ca: "Plorar", ipa: { inf: "/wiːp/", past: "/wept/", pp: "/wept/" }, ipaCa: "[pluˈra]" },
  { inf: "Wet", past: "Wet", pp: "Wet", es: "Mojar", ca: "Mullar", ipa: { inf: "/wet/", past: "/wet/", pp: "/wet/" }, ipaCa: "[muˈʎa]" },
  { inf: "Win", past: "Won", pp: "Won", es: "Ganar", ca: "Guanyar", ipa: { inf: "/wɪn/", past: "/wʌn/", pp: "/wʌn/" }, ipaCa: "[ɡwəˈɲa]" },
  { inf: "Wind", past: "Wound", pp: "Wound", es: "Enrollar", ca: "Enrotllar", ipa: { inf: "/waɪnd/", past: "/waʊnd/", pp: "/waʊnd/" }, ipaCa: "[ənrutˈʎa]" },
  { inf: "Withdraw", past: "Withdrew", pp: "Withdrawn", es: "Retirarse", ca: "Retirar-se", ipa: { inf: "/wɪðˈdrɔː/", past: "/wɪðˈdruː/", pp: "/wɪðˈdrɔːn/" }, ipaCa: "[rətiˈrarsə]" },
  { inf: "Wring", past: "Wrung", pp: "Wrung", es: "Torcer", ca: "Retorçar", ipa: { inf: "/rɪŋ/", past: "/rʌŋ/", pp: "/rʌŋ/" }, ipaCa: "[rəturˈsa]" },
  { inf: "Write", past: "Wrote", pp: "Written", es: "Escribir", ca: "Escriure", ipa: { inf: "/raɪt/", past: "/rəʊt/", pp: "/ˈrɪtən/" }, ipaCa: "[əsˈkɾiwɾə]" },
];

// Regular verbs, grouped by the pronunciation of the -ed ending (unique hook for a "sound sorting" mode)
// Corrections vs. source PDF (confirmed via Cambridge/Collins dictionaries):
//   - "Use" moved from /t/ to /d/ — "used" is pronounced /juːzd/ (voiced), not /t/.
//   - "Erase" moved from /t/ to /d/ — British "erase" is /ɪˈreɪz/ (voiced z), so "erased" = /ɪˈreɪzd/ (/d/ sound).
const REGULAR_VERBS = {
  id: [ // /ɪd/ sound — base ends in t or d
    { inf: "Accept", es: "Aceptar", ca: "Acceptar", ipaInf: "/əkˈsept/", ipaPast: "/əkˈseptɪd/", ipaCa: "[əksəpˈta]" },
    { inf: "Count", es: "Contar", ca: "Comptar", ipaInf: "/kaʊnt/", ipaPast: "/ˈkaʊntɪd/", ipaCa: "[kumˈta]" },
    { inf: "Date", es: "Citar", ca: "Datar", ipaInf: "/deɪt/", ipaPast: "/ˈdeɪtɪd/", ipaCa: "[dəˈta]" },
    { inf: "End", es: "Terminar", ca: "Acabar", ipaInf: "/end/", ipaPast: "/ˈendɪd/", ipaCa: "[əkəˈβa]" },
    { inf: "Expect", es: "Esperar", ca: "Esperar", ipaInf: "/ɪkˈspekt/", ipaPast: "/ɪkˈspektɪd/", ipaCa: "[əspəˈra]" },
    { inf: "Intend", es: "Intentar", ca: "Tenir la intenció", ipaInf: "/ɪnˈtend/", ipaPast: "/ɪnˈtendɪd/", ipaCa: "[təˈni lə intənˈsjo]" },
    { inf: "Need", es: "Necesitar", ca: "Necessitar", ipaInf: "/niːd/", ipaPast: "/ˈniːdɪd/", ipaCa: "[nəsəsiˈta]" },
    { inf: "Plant", es: "Plantar", ca: "Plantar", ipaInf: "/plɑːnt/", ipaPast: "/ˈplɑːntɪd/", ipaCa: "[plənˈta]" },
    { inf: "Point", es: "Señalar", ca: "Assenyalar", ipaInf: "/pɔɪnt/", ipaPast: "/ˈpɔɪntɪd/", ipaCa: "[əsəɲəˈla]" },
    { inf: "Rent", es: "Rentar", ca: "Llogar", ipaInf: "/rent/", ipaPast: "/ˈrentɪd/", ipaCa: "[ʎuˈɣa]" },
    { inf: "Repeat", es: "Repetir", ca: "Repetir", ipaInf: "/rɪˈpiːt/", ipaPast: "/rɪˈpiːtɪd/", ipaCa: "[rəpəˈti]" },
    { inf: "Resist", es: "Resistir", ca: "Resistir", ipaInf: "/rɪˈzɪst/", ipaPast: "/rɪˈzɪstɪd/", ipaCa: "[rəzisˈti]" },
    { inf: "Start", es: "Empezar", ca: "Començar", ipaInf: "/stɑːt/", ipaPast: "/ˈstɑːtɪd/", ipaCa: "[kumənˈsa]" },
    { inf: "Visit", es: "Visitar", ca: "Visitar", ipaInf: "/ˈvɪzɪt/", ipaPast: "/ˈvɪzɪtɪd/", ipaCa: "[biziˈta]" },
    { inf: "Wait", es: "Esperar", ca: "Esperar", ipaInf: "/weɪt/", ipaPast: "/ˈweɪtɪd/", ipaCa: "[əspəˈra]" },
    { inf: "Want", es: "Querer", ca: "Voler", ipaInf: "/wɒnt/", ipaPast: "/ˈwɒntɪd/", ipaCa: "[buˈle]" },
  ],
  t: [ // /t/ sound — base ends in unvoiced consonant
    { inf: "Ask", es: "Preguntar", ca: "Preguntar", ipaInf: "/ɑːsk/", ipaPast: "/ɑːskt/", ipaCa: "[prəɣunˈta]" },
    { inf: "Cook", es: "Cocinar", ca: "Cuinar", ipaInf: "/kʊk/", ipaPast: "/kʊkt/", ipaCa: "[kwiˈna]" },
    { inf: "Dance", es: "Bailar", ca: "Ballar", ipaInf: "/dɑːns/", ipaPast: "/dɑːnst/", ipaCa: "[bəˈʎa]" },
    { inf: "Dress", es: "Vestir", ca: "Vestir", ipaInf: "/dres/", ipaPast: "/drest/", ipaCa: "[bəsˈti]" },
    { inf: "Finish", es: "Terminar", ca: "Acabar", ipaInf: "/ˈfɪnɪʃ/", ipaPast: "/ˈfɪnɪʃt/", ipaCa: "[əkəˈβa]" },
    { inf: "Help", es: "Ayudar", ca: "Ajudar", ipaInf: "/help/", ipaPast: "/helpt/", ipaCa: "[əʒuˈða]" },
    { inf: "Jump", es: "Brincar, saltar", ca: "Saltar", ipaInf: "/dʒʌmp/", ipaPast: "/dʒʌmpt/", ipaCa: "[səlˈta]" },
    { inf: "Like", es: "Gustar", ca: "Agradar", ipaInf: "/laɪk/", ipaPast: "/laɪkt/", ipaCa: "[əɣɾəˈða]" },
    { inf: "Look", es: "Mirar", ca: "Mirar", ipaInf: "/lʊk/", ipaPast: "/lʊkt/", ipaCa: "[miˈra]" },
    { inf: "Miss", es: "Extrañar", ca: "Trobar a faltar", ipaInf: "/mɪs/", ipaPast: "/mɪst/", ipaCa: "[truˈβar ə fəlˈta]" },
    { inf: "Practice", es: "Practicar", ca: "Practicar", ipaInf: "/ˈpræktɪs/", ipaPast: "/ˈpræktɪst/", ipaCa: "[prəktiˈka]" },
    { inf: "Push", es: "Empujar", ca: "Empènyer", ipaInf: "/pʊʃ/", ipaPast: "/pʊʃt/", ipaCa: "[əmˈpɛɲə]" },
    { inf: "Shop", es: "Comprar", ca: "Comprar", ipaInf: "/ʃɒp/", ipaPast: "/ʃɒpt/", ipaCa: "[kumˈpra]" },
    { inf: "Smoke", es: "Fumar", ca: "Fumar", ipaInf: "/sməʊk/", ipaPast: "/sməʊkt/", ipaCa: "[fuˈma]" },
    { inf: "Stop", es: "Detener", ca: "Aturar", ipaInf: "/stɒp/", ipaPast: "/stɒpt/", ipaCa: "[ətuˈra]" },
    { inf: "Talk", es: "Hablar", ca: "Parlar", ipaInf: "/tɔːk/", ipaPast: "/tɔːkt/", ipaCa: "[pərˈla]" },
    { inf: "Walk", es: "Caminar", ca: "Caminar", ipaInf: "/wɔːk/", ipaPast: "/wɔːkt/", ipaCa: "[kəmiˈna]" },
    { inf: "Wash", es: "Lavar", ca: "Rentar", ipaInf: "/wɒʃ/", ipaPast: "/wɒʃt/", ipaCa: "[rənˈta]" },
    { inf: "Wish", es: "Desear", ca: "Desitjar", ipaInf: "/wɪʃ/", ipaPast: "/wɪʃt/", ipaCa: "[dəziˈdʒa]" },
    { inf: "Work", es: "Trabajar", ca: "Treballar", ipaInf: "/wɜːk/", ipaPast: "/wɜːkt/", ipaCa: "[trəβəˈʎa]" },
  ],
  d: [ // /d/ sound — base ends in voiced consonant or vowel
    { inf: "Answer", es: "Responder", ca: "Respondre", ipaInf: "/ˈɑːnsə/", ipaPast: "/ˈɑːnsəd/", ipaCa: "[rəsˈpɔndɾə]" },
    { inf: "Arrive", es: "Llegar, arribar", ca: "Arribar", ipaInf: "/əˈraɪv/", ipaPast: "/əˈraɪvd/", ipaCa: "[əriˈβa]" },
    { inf: "Belong", es: "Pertenecer", ca: "Pertànyer", ipaInf: "/bɪˈlɒŋ/", ipaPast: "/bɪˈlɒŋd/", ipaCa: "[pərˈtaɲə]" },
    { inf: "Change", es: "Cambiar", ca: "Canviar", ipaInf: "/tʃeɪndʒ/", ipaPast: "/tʃeɪndʒd/", ipaCa: "[kəmbiˈa]" },
    { inf: "Clean", es: "Limpiar", ca: "Netejar", ipaInf: "/kliːn/", ipaPast: "/kliːnd/", ipaCa: "[nətəˈʒa]" },
    { inf: "Climb", es: "Escalar", ca: "Escalar", ipaInf: "/klaɪm/", ipaPast: "/klaɪmd/", ipaCa: "[əskəˈla]" },
    { inf: "Close", es: "Cerrar", ca: "Tancar", ipaInf: "/kləʊz/", ipaPast: "/kləʊzd/", ipaCa: "[təŋˈka]" },
    { inf: "Consider", es: "Considerar", ca: "Considerar", ipaInf: "/kənˈsɪdə/", ipaPast: "/kənˈsɪdəd/", ipaCa: "[kunsidəˈra]" },
    { inf: "Dare", es: "Retar", ca: "Atrevir-se", ipaInf: "/deə/", ipaPast: "/deəd/", ipaCa: "[ətrəˈβirsə]" },
    { inf: "Deliver", es: "Entregar", ca: "Lliurar", ipaInf: "/dɪˈlɪvə/", ipaPast: "/dɪˈlɪvəd/", ipaCa: "[ʎiwˈra]" },
    { inf: "Enjoy", es: "Disfrutar", ca: "Gaudir", ipaInf: "/ɪnˈdʒɔɪ/", ipaPast: "/ɪnˈdʒɔɪd/", ipaCa: "[ɡəwˈði]" },
    { inf: "Erase", es: "Borrar", ca: "Esborrar", ipaInf: "/ɪˈreɪz/", ipaPast: "/ɪˈreɪzd/", ipaCa: "[əzbuˈra]" },
    { inf: "Fill", es: "Llenar", ca: "Omplir", ipaInf: "/fɪl/", ipaPast: "/fɪld/", ipaCa: "[umˈpli]" },
    { inf: "Follow", es: "Seguir", ca: "Seguir", ipaInf: "/ˈfɒləʊ/", ipaPast: "/ˈfɒləʊd/", ipaCa: "[səˈɣi]" },
    { inf: "Hurry", es: "Apurar, darse prisa", ca: "Afanyar-se", ipaInf: "/ˈhʌri/", ipaPast: "/ˈhʌrid/", ipaCa: "[əfəˈɲarsə]" },
    { inf: "Learn", es: "Aprender", ca: "Aprendre", ipaInf: "/lɜːn/", ipaPast: "/lɜːnd/", ipaCa: "[əˈpɾɛndɾə]" },
    { inf: "Listen", es: "Escuchar", ca: "Escoltar", ipaInf: "/ˈlɪsən/", ipaPast: "/ˈlɪsənd/", ipaCa: "[əskulˈta]" },
    { inf: "Live", es: "Vivir", ca: "Viure", ipaInf: "/lɪv/", ipaPast: "/lɪvd/", ipaCa: "[ˈbiwɾə]" },
    { inf: "Love", es: "Amar", ca: "Estimar", ipaInf: "/lʌv/", ipaPast: "/lʌvd/", ipaCa: "[əstiˈma]" },
    { inf: "Name", es: "Nombrar", ca: "Anomenar", ipaInf: "/neɪm/", ipaPast: "/neɪmd/", ipaCa: "[ənumuˈna]" },
    { inf: "Open", es: "Abrir", ca: "Obrir", ipaInf: "/ˈəʊpən/", ipaPast: "/ˈəʊpənd/", ipaCa: "[uˈβɾi]" },
    { inf: "Order", es: "Ordenar", ca: "Ordenar", ipaInf: "/ˈɔːdə/", ipaPast: "/ˈɔːdəd/", ipaCa: "[urðəˈna]" },
    { inf: "Plan", es: "Planear", ca: "Planejar", ipaInf: "/plæn/", ipaPast: "/plænd/", ipaCa: "[pləˈnəʒa]" },
    { inf: "Play", es: "Jugar", ca: "Jugar", ipaInf: "/pleɪ/", ipaPast: "/pleɪd/", ipaCa: "[ʒuˈɣa]" },
    { inf: "Rain", es: "Llover", ca: "Ploure", ipaInf: "/reɪn/", ipaPast: "/reɪnd/", ipaCa: "[ˈplɔwɾə]" },
    { inf: "Remember", es: "Recordar", ca: "Recordar", ipaInf: "/rɪˈmembə/", ipaPast: "/rɪˈmembəd/", ipaCa: "[rəkurˈða]" },
    { inf: "Show", es: "Mostrar", ca: "Mostrar", ipaInf: "/ʃəʊ/", ipaPast: "/ʃəʊd/", ipaCa: "[musˈtra]" },
    { inf: "Stay", es: "Permanecer", ca: "Quedar-se", ipaInf: "/steɪ/", ipaPast: "/steɪd/", ipaCa: "[kəˈðarsə]" },
    { inf: "Study", es: "Estudiar", ca: "Estudiar", ipaInf: "/ˈstʌdi/", ipaPast: "/ˈstʌdid/", ipaCa: "[əstuðiˈa]" },
    { inf: "Travel", es: "Viajar", ca: "Viatjar", ipaInf: "/ˈtrævəl/", ipaPast: "/ˈtrævəld/", ipaCa: "[biəˈdʒa]" },
    { inf: "Try", es: "Intentar, tratar", ca: "Intentar, Provar", ipaInf: "/traɪ/", ipaPast: "/traɪd/", ipaCa: "[intənˈta]" },
    { inf: "Turn", es: "Voltear, dar vuelta", ca: "Girar", ipaInf: "/tɜːn/", ipaPast: "/tɜːnd/", ipaCa: "[ʒiˈra]" },
    { inf: "Use", es: "Usar", ca: "Utilitzar", ipaInf: "/juːz/", ipaPast: "/juːzd/", ipaCa: "[utiliˈdza]" },
  ],
};

// Helper: builds the real past-tense spelling for a regular verb given its base rules
// -ed suffix rule: if base ends in "e", add "d"; else add "ed" (irregular-spelling verbs like
// study->studied, stop->stopped are pre-resolved to their real past forms via overrides)
// Correction vs. source PDF: "Plan" was mistyped as "Planed" (the woodworking verb "to plane") — correct form is "Planned".
const REGULAR_PAST_OVERRIDES = {
  Study: "Studied", Hurry: "Hurried", Try: "Tried", Plan: "Planned", Shop: "Shopped", Stop: "Stopped",
};

function regularPastForm(inf) {
  if (REGULAR_PAST_OVERRIDES[inf]) return REGULAR_PAST_OVERRIDES[inf];
  if (inf.endsWith("e")) return inf + "d";
  return inf + "ed";
}

if (typeof module !== "undefined") {
  module.exports = { IRREGULAR_VERBS, REGULAR_VERBS, regularPastForm };
}
